DROP TABLE IF EXISTS autor;
DROP TABLE IF EXISTS book;

CREATE TABLE autor (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL
);

CREATE TABLE book (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  published TIMESTAMP NOT NULL,
  title TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES autor (id)
);